#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use AdventOfCode\Challenges\Eight\HandheldHaltingCommand;
use AdventOfCode\Challenges\Eleven\SeatingSystemCommand;
use AdventOfCode\Challenges\Five\BinaryBoardingCommand;
use AdventOfCode\Challenges\Four\PassportProcessing;
use AdventOfCode\Challenges\Nine\EncodingErrorCommand;
use AdventOfCode\Challenges\One\ReportRepairCommand;
use AdventOfCode\Challenges\Seven\HandyHaversacksCommands;
use AdventOfCode\Challenges\Six\CustomCustomsCommand;
use AdventOfCode\Challenges\Ten\AdapterArrayCommand;
use AdventOfCode\Challenges\Three\TobogganTrajectoryCommand;
use AdventOfCode\Challenges\Twelve\RainRiskCommand;
use AdventOfCode\Challenges\Two\PasswordPhilosophyCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands(
    [
        new ReportRepairCommand(),
        new PasswordPhilosophyCommand(),
        new TobogganTrajectoryCommand(),
        new PassportProcessing(),
        new BinaryBoardingCommand(),
        new CustomCustomsCommand(),
        new HandyHaversacksCommands(),
        new HandheldHaltingCommand(),
        new EncodingErrorCommand(),
        new AdapterArrayCommand(),
        new SeatingSystemCommand(),
        new RainRiskCommand(),
    ]
);

$application->run();
