#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use AdventOfCode\Challenges\One\ReportRepairCommand;
use AdventOfCode\Challenges\Two\PasswordPhilosophyCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands(
    [
        new ReportRepairCommand(),
        new PasswordPhilosophyCommand()
    ]
);

$application->run();
